// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCD-OOOoIfjAEa1kNj7uwn-I8IqSXIhY54',
    appId: '1:22545897388:web:5f93a40ff994a5f9140c09',
    messagingSenderId: '22545897388',
    projectId: 'lap-2f45d',
    authDomain: 'lap-2f45d.firebaseapp.com',
    storageBucket: 'lap-2f45d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFrqzV2xjHIGNCPsOlpe78BFpywmtvZgI',
    appId: '1:22545897388:android:f5edf2efec3a115d140c09',
    messagingSenderId: '22545897388',
    projectId: 'lap-2f45d',
    storageBucket: 'lap-2f45d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvHCgeX3atAkE66sTjJaMYy56KmBn9u-I',
    appId: '1:22545897388:ios:8766ceff7dadd7a5140c09',
    messagingSenderId: '22545897388',
    projectId: 'lap-2f45d',
    storageBucket: 'lap-2f45d.appspot.com',
    iosClientId: '22545897388-glljn475a2me6sgppdqhromfcjb3mkp2.apps.googleusercontent.com',
    iosBundleId: 'com.example.lap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvHCgeX3atAkE66sTjJaMYy56KmBn9u-I',
    appId: '1:22545897388:ios:8766ceff7dadd7a5140c09',
    messagingSenderId: '22545897388',
    projectId: 'lap-2f45d',
    storageBucket: 'lap-2f45d.appspot.com',
    iosClientId: '22545897388-glljn475a2me6sgppdqhromfcjb3mkp2.apps.googleusercontent.com',
    iosBundleId: 'com.example.lap',
  );
}
